### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/freckler#4]
@schmierkov @mauro-oto we should use this license: https://opensource.org/licenses/MIT

**Comment by schmierkov** [comment]
@etagwerker what is the difference to the current license? https://github.com/ombulabs/freckler/blob/master/LICENSE

**Comment by mauro-oto** [comment]
@schmierkov maybe the README should include a mention of the MIT license instead of the current copyright notice, see this for an example: https://github.com/thoughtbot/bourbon#license
